In [149]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [150]:
dataset = pd.read_csv('HousingData.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [151]:
print(X)

[[6.32e-03 1.80e+01 2.31e+00 ... 1.53e+01 3.97e+02 4.98e+00]
 [2.73e-02 0.00e+00 7.07e+00 ... 1.78e+01 3.97e+02 9.14e+00]
 [2.73e-02 0.00e+00 7.07e+00 ... 1.78e+01 3.93e+02 4.03e+00]
 ...
 [6.08e-02 0.00e+00 1.19e+01 ... 2.10e+01 3.97e+02 5.64e+00]
 [1.10e-01 0.00e+00 1.19e+01 ... 2.10e+01 3.93e+02 6.48e+00]
 [4.74e-02 0.00e+00 1.19e+01 ... 2.10e+01 3.97e+02 7.88e+00]]


In [152]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [153]:
print(X)

[[  1.     0.     0.   ...  15.3  396.9    4.98]
 [  1.     0.     0.   ...  17.8  396.9    9.14]
 [  1.     0.     0.   ...  17.8  392.83   4.03]
 ...
 [  1.     0.     0.   ...  21.   396.9    5.64]
 [  1.     0.     0.   ...  21.   393.45   6.48]
 [  1.     0.     0.   ...  21.   396.9    7.88]]


In [154]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [156]:
from sklearn.linear_model import PolynomialRegression
regressor =  PolynomialRegression()
regressor.fit(X_train, y_train)

ImportError: cannot import name 'PolynomialRegression' from 'sklearn.linear_model' (d:\user\anaconda\lib\site-packages\sklearn\linear_model\__init__.py)

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]
